import PDFDocument from "pdfkit";

/* =========================================
   BRANDED REPORT CARD PDF GENERATOR
========================================= */

export function generateBrandedReportCardPDF(reportCard, res, school = {}) {
  const doc = new PDFDocument({
    size: "A4",
    margin: 40,
  });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename=${reportCard.student.admissionNumber}_report_card.pdf`
  );

  doc.pipe(res);

  /* =========================================
     SCHOOL HEADER (BRANDING)
  ========================================= */

  if (school.logoUrl) {
    try {
      doc.image(school.logoUrl, 40, 30, {
        width: 60,
      });
    } catch (e) {
      // ignore broken image
    }
  }

  doc
    .fillColor("#1E3A8A")
    .fontSize(18)
    .text(school.name || "SCHOOL NAME", 120, 35);

  doc
    .fillColor("#444")
    .fontSize(10)
    .text(school.address || "", 120, 55);

  /* Divider */
  doc.moveTo(40, 85).lineTo(550, 85).stroke("#1E3A8A");

  /* =========================================
     STUDENT HEADER CARD
  ========================================= */

  doc.moveDown(2);

  doc
    .fillColor("#000")
    .fontSize(14)
    .text(
      `Student Report Card`,
      { align: "center" }
    );

  doc.moveDown(1);

  doc
    .fontSize(11)
    .text(`Name: ${reportCard.student.firstName} ${reportCard.student.lastName}`)
    .text(`Admission No: ${reportCard.student.admissionNumber}`)
    .text(`Class: ${reportCard.student.className}`)
    .text(`Session: ${reportCard.session.name}`)
    .text(`Term: ${reportCard.term.name}`);

  /* =========================================
     POSITION BADGE
  ========================================= */

  doc
    .moveDown()
    .fillColor("#16A34A")
    .fontSize(12)
    .text(
      `Position: ${reportCard.summary.positionLabel}`,
      { align: "right" }
    );

  doc.moveDown();

  /* =========================================
     TABLE HEADER
  ========================================= */

  const startY = doc.y + 10;

  const col = {
    subject: 50,
    ca1: 260,
    ca2: 310,
    assign: 360,
    exam: 420,
    total: 470,
    grade: 520,
  };

  doc
    .fillColor("#1E3A8A")
    .fontSize(10)
    .text("Subject", col.subject, startY)
    .text("CA1", col.ca1, startY)
    .text("CA2", col.ca2, startY)
    .text("ASS", col.assign, startY)
    .text("EXAM", col.exam, startY)
    .text("TOTAL", col.total, startY)
    .text("GRADE", col.grade, startY);

  doc.moveTo(40, startY + 15).lineTo(550, startY + 15).stroke();

  /* =========================================
     RESULTS ROWS
  ========================================= */

  let y = startY + 25;

  reportCard.results.forEach((r, i) => {
    const shade = i % 2 === 0 ? "#F8FAFC" : "#FFFFFF";

    doc.rect(40, y - 5, 510, 18).fill(shade);

    doc
      .fillColor("#000")
      .fontSize(9)
      .text(r.subjectName, col.subject, y)
      .text(String(r.ca1), col.ca1, y)
      .text(String(r.ca2), col.ca2, y)
      .text(String(r.assignment), col.assign, y)
      .text(String(r.exam), col.exam, y)
      .text(String(r.total), col.total, y)
      .text(r.grade, col.grade, y);

    y += 18;
  });

  /* =========================================
     SUMMARY BOX
  ========================================= */

  doc.moveDown(2);

  doc
    .fillColor("#111827")
    .fontSize(12)
    .text("ACADEMIC SUMMARY", { underline: true });

  doc
    .fontSize(10)
    .text(`Total Score: ${reportCard.summary.totalScore}`)
    .text(`Average: ${reportCard.summary.averageScore}`)
    .text(`Subjects: ${reportCard.summary.subjectsCount}`);

  /* =========================================
     ATTENDANCE
  ========================================= */

  doc.moveDown();

  doc
    .fontSize(12)
    .text("ATTENDANCE SUMMARY", { underline: true });

  doc
    .fontSize(10)
    .text(`Total Days: ${reportCard.attendance.total}`)
    .text(`Present: ${reportCard.attendance.present}`)
    .text(`Absent: ${reportCard.attendance.absent}`)
    .text(`Late: ${reportCard.attendance.late}`);

  /* =========================================
     FOOTER
  ========================================= */

  doc
    .moveDown(2)
    .fontSize(9)
    .fillColor("#6B7280")
    .text(
      "Generated by EduTrack • Academic Management System",
      { align: "center" }
    );

  doc.end();
}